정규화 : X / 수고 / 수관폭평균 / 9월 1일 새순 / 엽록소 / 10월 1일 새순 / 엽록소

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

In [3]:
path = '/content/drive/MyDrive/ P - value/proj_3/데이터 파일/전처리데이터 (전후)/X_date.csv'

phh_X_date = pd.read_csv(path)
phh_X_date

,2022-09-01 새순,2022-09-02 새순,2022-09-03 새순,2022-09-04 새순,2022-09-05 새순,2022-09-06 새순,2022-09-07 새순,2022-09-08 새순,2022-09-09 새순,2022-09-10 새순,...,2022-11-19 엽록소,2022-11-20 엽록소,2022-11-21 엽록소,2022-11-22 엽록소,2022-11-23 엽록소,2022-11-24 엽록소,2022-11-25 엽록소,2022-11-26 엽록소,2022-11-27 엽록소,2022-11-28 엽록소
0,2.8,2.8,2.7,2.7,2.7,2.7,2.6,2.6,2.6,2.6,...,70.978249,70.876794,70.705253,70.559603,70.427356,70.340491,70.293830,70.262422,70.169841,70.043251
1,3.3,3.3,3.3,3.2,3.2,3.1,3.1,3.1,3.0,3.0,...,71.535483,71.382303,71.253604,71.092665,70.955608,70.796630,70.597550,70.565088,70.560502,70.427600
2,3.0,2.9,2.9,2.9,2.9,2.8,2.8,2.8,2.8,2.7,...,71.279804,71.199570,71.144020,71.026740,70.920038,70.876723,70.710129,70.595971,70.418203,70.399578
3,3.1,3.0,3.0,3.0,3.0,2.9,2.9,2.9,2.8,2.8,...,69.934615,69.884124,69.845683,69.794682,69.779813,69.614644,69.455404,69.281590,69.238689,69.133970
4,3.7,3.6,3.6,3.6,3.5,3.5,3.5,3.4,3.4,3.3,...,68.313016,68.285364,68.209860,68.209458,68.040083,67.859963,67.775556,67.701456,67.504244,67.410093
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2202,4.7,4.6,4.5,4.5,4.4,4.4,4.3,4.3,4.2,4.2,...,66.347384,66.293609,66.193131,66.176590,66.109845,66.008775,65.889675,65.734066,65.586656,65.560547
2203,3.1,3.0,3.0,3.0,2.9,2.9,2.9,2.9,2.8,2.8,...,73.438844,73.432194,73.355195,73.329491,73.271361,73.088750,73.071705,73.069036,72.952559,72.944396
2204,3.0,3.0,2.9,2.9,2.9,2.9,2.8,2.8,2.8,2.8,...,67.576066,67.404347,67.394009,67.247428,67.117025,66.933771,66.734617,66.572095,66.506006,66.479459
2205,3.9,3.9,3.8,3.8,3.8,3.7,3.7,3.6,3.6,3.6,...,66.766379,66.602606,66.510781,66.334637,66.323613,66.248731,66.202532,66.108962,65.934979,65.812084
2206,5.3,5.2,5.2,5.1,5.0,5.0,4.9,4.9,4.8,4.8,...,72.885385,72.734930,72.629823,72.454654,72.389570,72.271680,72.208433,72.070977,71.872453,71.870512

In [4]:
path = '/content/drive/MyDrive/ P - value/proj_3/데이터 파일/전처리데이터 (전후)/y.csv'

phh_y = pd.read_csv(path)
phh_y

      착과량(int)
0          692
1          534
2          634
3          639
4          496
...        ...
2202       119
2203       611
2204       650
2205       363
2206        17

[2207 rows x 1 columns]

In [5]:
path = '/content/drive/MyDrive/ P - value/proj_3/데이터 파일/전처리데이터 (전후)/X.csv'

phh_X = pd.read_csv(path)
phh_X

      수고(m)  수관폭1(min)  수관폭2(max)  수관폭평균
0     275.0      287.0      292.0  289.5
1     293.0      284.0      336.0  310.0
2     300.0      392.0      450.0  421.0
3     289.0      368.0      379.0  373.5
4     306.0      353.0      358.0  355.5
...     ...        ...        ...    ...
2202  230.0      353.0      367.0  360.0
2203  266.0      337.0      400.0  368.5
2204  237.0      353.0      362.0  357.5
2205  281.0      337.0      403.0  370.0
2206  228.0      389.0      398.0  393.5

[2207 rows x 4 columns]

In [6]:
phh = phh_y.loc[:, '착과량(int)'].copy()

In [7]:
phh = pd.concat([phh, phh_X[['수고(m)', '수관폭평균']]], axis=1)
phh = pd.concat([phh, phh_X_date[['2022-09-01 새순', '2022-10-01 새순', '2022-09-01 엽록소', '2022-10-01 엽록소']]], axis=1)

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [10]:
# X, y 나눠주기
X = phh.drop('착과량(int)', axis=1)  # 변수 열들을 X로 설정
y = phh['착과량(int)']  # 타겟 열을 y로 설정

# Train-Test 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=3)

# Random Forest Classifier 모델 생성 및 학습
rf = RandomForestClassifier(random_state=3)
rf.fit(X_train, y_train)

# 테스트 데이터에 대한 예측
y_pred = rf.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score

# 정확도를 계산해보자
accuracy = accuracy_score(y_test, y_pred)

print("정확도 : ", accuracy)

정확도 :  0.010558069381598794

In [12]:
import numpy as np

# 예측값과 실제값의 차이 계산
errors = np.abs(y_pred - y_test)

# 오차 범위 통계량 계산
mean_error = np.mean(errors)
max_error = np.max(errors)
min_error = np.min(errors)
median_error = np.median(errors)
std_error = np.std(errors)

print("Mean Error:", mean_error)
print("Max Error:", max_error)
print("Min Error:", min_error)
print("Median Error:", median_error)
print("Standard Deviation of Error:", std_error)

Mean Error: 41.295625942684765
Max Error: 185
Min Error: 0
Median Error: 32.0
Standard Deviation of Error: 36.042334277956705

# 전처리를 안한 데이터가 정확도는 좀 더 높게나왔다 하지만 망했다.